# This file is auto-generated by MACH composer
# SiteComponent: test-1/component-1
terraform {
  backend "gcs" {
    bucket = "state-bucket"
    prefix = "mach-composer/test-1/component-1"
  }
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 4.69.1"
    }
  }
}

# File sources
# Resources
provider "google" {
  project = ""
  region  = ""
  zone    = ""
}

# Component: component-1
module "component-1" {
  source            = "{{ .PWD }}/testdata/modules/application"
  variables         = {}
  secrets           = {}
  component_version = "test"
  environment       = "test"
  site              = "test-1"
  tags              = local.tags
  providers = {
    provider = google,
  }
}

output "component-1" {
  description = "The module outputs for component-1"
  sensitive   = true
  value       = module.component-1
}
