# This file is auto-generated by MACH Framework
# Site: {{ site.identifier }}

terraform {
  {% if general_config.terraform_config.azure_remote_state %}
  {% set azure_config = general_config.terraform_config.azure_remote_state %}
  backend "azurerm" {
    resource_group_name  = "{{ azure_config.resource_group_name }}"
    storage_account_name = "{{ azure_config.storage_account_name }}"
    container_name       = "{{ azure_config.container_name }}"
    key                  = "{{ azure_config.state_folder}}/{{ site.identifier }}"
  }
  {% endif %}
}

provider "azurerm" {
  version = "=2.29.0"
  {% if site.azure %}
  subscription_id = "{{ site.azure.subscription_id }}"
  tenant_id       = "{{ site.azure.tenant_id }}"
  skip_provider_registration = true
  {% endif %}
  features {}
}

{% include 'partials/commercetools.tf' %}

{% include 'partials/azure.tf' %}

{% include 'partials/components.tf' %}