project_name: mach-composer

env:
  - SKIP_UPLOAD={{ if index .Env "SKIP_UPLOAD"  }}{{ .Env.SKIP_UPLOAD }}{{ else }}false{{ end }}

before:
  hooks:
    - task tidy
    - task download

# Build step
builds:
  - id: mach-composer
    main: .
    binary: bin/mach-composer
    flags:
      - -trimpath
      - -tags=netgo
    env:
      - CGO_ENABLED=0
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    ldflags: |
      -s -w
        -X github.com/mach-composer/mach-composer-cli/internal/cli.version={{.Version}}
        -X github.com/mach-composer/mach-composer-cli/internal/cli.commit={{.Commit}}
        -X github.com/mach-composer/mach-composer-cli/internal/cli.date={{.CommitDate}}
        -extldflags '-static'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    mod_timestamp: '{{ .CommitTimestamp }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

# Publish step
release:
  mode: replace
  prerelease: auto

changelog:
  use: github
  disable: false

archives:
  - id: mach-composer
    name_template: "mach-composer-{{.Version}}-{{.Os}}-{{.Arch}}{{ if .Arm }}v{{.Arm }}{{ end }}"
    format: tar.gz
    files:
      - LICENSE
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: "{{ .ProjectName }}"
    skip_upload: "{{ .Env.SKIP_UPLOAD }}"
    repository:
      owner: mach-composer
      name: homebrew-{{ .ProjectName }}
    url_template: https://github.com/mach-composer/mach-composer-cli/releases/download/v{{ .Version }}/{{ .ArtifactName }}
    commit_author:
      name: goreleaserbot
      email: opensource@labdigital.nl
    homepage: "https://machcomposer.io/"
    description: |
      MACH composer is a framework that you use to orchestrate and extend
      modern digital commerce & experience platforms, based on MACH
      technologies and cloud native services..
    license: "MIT"
    dependencies:
      - name: terraform
      - name: git
        type: optional

chocolateys:
  - title: MACH composer
    owners: Lab
    authors: Lab Digital
    project_url: https://machcomposer.io/
    license_url: https://github.com/mach-composer/mach-composer-cli/blob/main/LICENSE
    project_source_url: https://github.com/mach-composer/mach-composer-cli
    docs_url: https://docs.machcomposer.io
    bug_tracker_url: https://github.com/mach-composer/mach-composer-cli/issues
    url_template: "https://github.com/mach-composer/mach-composer-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    icon_url: 'https://avatars.githubusercontent.com/u/82937813?s=200&v=4'
    copyright: 2020-2022 Lab Digital
    tags: "mach terraform"
    summary: A framework to orchestrate MACH platforms
    description: |
      MACH composer is a framework that you use to orchestrate and extend
      modern digital commerce & experience platforms, based on MACH
      technologies and cloud native services..
    release_notes: "https://github.com/mach-composer/mach-composer-cli/releases/tag/v{{ .Version }}"
    api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'

    #TODO: Re-enable this when we have a working chocolaty registry
    #    skip_publish: "{{ .Env.SKIP_UPLOAD }}"
    skip_publish: true

nix:
  - name: mach-composer
    url_template: https://github.com/mach-composer/mach-composer-cli/releases/download/v{{ .Version }}/{{ .ArtifactName }}
    commit_author:
      name: goreleaserbot
      email: opensource@labdigital.nl
    path: pkgs/mach-composer.nix
    description: "Orchestration tool for modern MACH ecosystems, powered by Terraform infrastructure-as-code underneath"
    homepage: "https://www.machcomposer.io/"
    license: "mit"
    skip_upload: "{{ .Env.SKIP_UPLOAD }}"
    dependencies:
      - git
      - terraform
    # go-releaser tries to cp bin/mach-composer store/bin/bin/mach-composer
    # override install step to fix that. dependencies need redefining here :(
    install: |
      mkdir -p $out/bin
      cp -vr ./bin/mach-composer $out/bin/mach-composer
      wrapProgram $out/bin/mach-composer --prefix PATH : ${lib.makeBinPath ([ git terraform ])}
    post_install: |
      installShellCompletion --cmd mach-composer \
        --bash <($out/bin/mach-composer completion bash) \
        --fish <($out/bin/mach-composer completion fish) \
        --zsh <($out/bin/mach-composer completion zsh)
    repository:
      owner: mach-composer
      name: nix-{{ .ProjectName }}
