version: '3'

includes:
  docs:
    taskfile: ./docs/Taskfile.yaml
    dir: ./docs

tasks:
  build:
    env:
      GORELEASER_CURRENT_TAG: "v0.0.0"
    cmd: goreleaser build --snapshot --clean --single-target --output mach-composer

  download:
    cmd: go mod download

  tidy:
    cmd: go mod tidy -v

  generate:
    cmd: go generate ./...

  test:
    cmd: go test -race ./...

  test:integration:
    cmd: go test -tags=integration ./...

  cover:
    cmd: go test -race -coverprofile=coverage.out -covermode=atomic ./...

  cover-html:
    cmds:
      - task cover
      - go tool cover -html=coverage.out -o coverage.html

  docker:
    cmd: docker build -t docker.pkg.github.com/mach-composer/mach-composer-cli/mach:latest . --progress=plain

