# This file is auto-generated by MACH composer
# SiteComponent: test-1/component-1
terraform {
  backend "azurerm" {
    resource_group_name  = "resourcegroupid"
    storage_account_name = "storageaccount"
    container_name       = "container-name"
    key                  = "test-1/component-1"
  }
  required_providers {}
}

# File sources
# Resources
# Component: component-1
module "component-1" {
  source            = "/home/thomas/Projects/mach-composer/mach-composer-cli/internal/cmd/testdata/modules/application"
  variables         = {}
  secrets           = {}
  component_version = "test"
  environment       = "test"
  site              = "test-1"
  tags              = local.tags
}

output "component-1" {
  description = "The module outputs for component-1"
  sensitive   = true
  value       = module.component-1
}
