# This file is auto-generated by MACH composer
# SiteComponent: test-1/component-2
terraform {
  backend "s3" {
    bucket         = "state-bucket"
    key            = "mach-composer/test-1/component-2"
    region         = "eu-west-1"
    dynamodb_table = "lock-table"
    encrypt        = true
  }
  required_providers {}
}

# File sources
# Resources
data "terraform_remote_state" "test-1" {
  backend = "s3"
  config = {
    bucket         = "state-bucket"
    key            = "mach-composer/test-1"
    region         = "eu-west-1"
    dynamodb_table = "lock-table"
    encrypt        = true
  }
}

# Component: component-2
module "component-2" {
  source = "{{ .PWD }}/testdata/modules/application"
  variables = {
    parent_names = [data.terraform_remote_state.test-1.outputs.component-1.name]
  }
  component_version = "test"
  environment       = "test"
  site              = "test-1"
  tags              = { "Component" : "component-2", "Site" : "test-1", "Version" : "test" }
}

output "component-2" {
  description = "The module outputs for component-2"
  sensitive   = true
  value       = module.component-2
}
