# This file is auto-generated by MACH composer
# site: test-1
terraform {
  backend "gcs" {
    bucket = "state-bucket"
    prefix = "mach-composer/test-1"
  }
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 4.69.1"
    }
  }
}

# File sources
# Resources
provider "google" {
  project = ""
  region  = ""
  zone    = ""
}
