# This file is auto-generated by MACH composer
# SiteComponent: test-2/component-1
terraform {
  backend "s3" {
    bucket         = "state-bucket"
    key            = "mach-composer/test-2/component-1"
    region         = "eu-west-1"
    dynamodb_table = "lock-table"
    encrypt        = true
  }
  required_providers {}
}

# File sources
# Resources
# Component: component-1
module "component-1" {
  source            = "{{ .PWD }}/testdata/modules/application"
  component_version = "test"
  environment       = "test"
  site              = "test-2"
  tags              = { "Component" : "component-1", "Site" : "test-2", "Version" : "test" }
}

output "component-1" {
  description = "The module outputs for component-1"
  sensitive   = true
  value       = module.component-1
}
