# This file is auto-generated by MACH composer
# site: test-2
terraform {
  backend "s3" {
    bucket         = "state-bucket"
    key            = "mach-composer/test-2"
    region         = "eu-west-1"
    dynamodb_table = "lock-table"
    encrypt        = true
  }
  required_providers {}
}

# File sources
# Resources