# This file is auto-generated by MACH composer
# site: test-1
terraform {
  backend "azurerm" {
    key                  = "test-1"
    storage_account_name = "storageaccount"
    container_name       = "container-name"
    resource_group_name  = "resourcegroupid"
  }
  required_providers {}
}

# File sources
# Resources
