# This file is auto-generated by MACH composer
# SiteComponent: test-1/component-2
terraform {
  backend "local" {
    path = "./states/test-1/component-2.tfstate"
  }
  required_providers {
    aws = {
      version = "~> 3.74.1"
    }
  }
}

# File sources
# Resources
# Configuring AWS
provider "aws" {
  region = "eu-west-1"
}

locals {
  tags = {
    Site        = "test-1"
    Environment = "test"
  }
}

# Component: component-2
module "component-2" {
  source            = "{{ .PWD }}/testdata/modules/application"
  variables         = {}
  secrets           = {}
  component_version = "main"
  environment       = "test"
  site              = "test-1"
  tags              = local.tags
  providers = {
    aws = aws,
  }
}

output "component-2" {
  description = "The module outputs for component-2"
  sensitive   = true
  value       = module.component-2
}
