version: '3'

tasks:
  default:
    silent: true
    cmd: task --list-all

  install:
    cmd: pip install -r requirements.txt

  generate:
    dir: ../
    cmds:
      - go generate ./...
      - cp internal/config/schemas/schema-1.yaml docs/src/reference/syntax/schema.yaml

  preview:
    deps:
      - install
    cmd: mkdocs serve

  docker-image:
    cmd: docker build -t docs .

  docker-build:
    cmds:
      - docker run --name docs docs mkdocs build -d /build
      - docker cp src:/build .
      - docker rm -f docs

  clean:
    cmd: rm -rf build
