# This file is auto-generated by MACH composer
# site: test-1
terraform {
  backend "local" {
    path = "./states/test-1.tfstate"
  }
  required_providers {}
}

# File sources
# Resources
# Component: component-1
module "component-1" {
  source = "/home/thomas/Projects/mach-composer/mach-composer-cli/internal/cmd/testdata/modules/application"
}

output "component-1" {
  description = "The module outputs for component-1"
  sensitive   = true
  value       = module.component-1
}

# Component: component-2
module "component-2" {
  source = "/home/thomas/Projects/mach-composer/mach-composer-cli/internal/cmd/testdata/modules/application"
}

output "component-2" {
  description = "The module outputs for component-2"
  sensitive   = true
  value       = module.component-2
}
